### ISSUE TITLE
FREE VS tfvaegan

### ISSUE THREAD

**Issue by in-my-heart** [shiming-chen/FREE#1]
In the process of reading your paper, I always feel like tfvaegan. I can confirm from your code that you refer to tfvaegan. Except you removed the feedback module of tfvaegan and proposed SAMC-loss. Or from your code, it can be said that the feedback module is replaced with SAMC-loss.  Could the author point out other differences between your paper and eccv2020: [tfvaegan](https://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123670477.pdf) . The FR you proposed is basically the same as tfvaegan's decoder?

**Comment by shiming-chen** [comment]
Hi, @in-my-heart,
Thank you for interesting in our work. As you can see, TF-VAEGAN and our FREE incorporate an additional module on the top of the [f-VAEGAN-D2,](https://openaccess.thecvf.com/content_CVPR_2019/papers/Xian_F-VAEGAN-D2_A_Feature_Generating_Framework_for_Any-Shot_Learning_CVPR_2019_paper.pdf) but there are some obvious differences between them as follows:
1) **Motivation Difference**: TF-VAEGAN aims to  enforce semantic consistency at all stages of ZSL: training, feature synthesis and classification, while our FREE aims to tackle the cross-dataset bias problem .
2) **Technical Difference**: Dec of TF-VAEGAN maps visual features into a semantic space with a typical MLP cooperated with a feedback mechanism (this is the main contribution of TF-VAEGAN). FR  of our FREE embeds the visual features into a the semantic space with a well-designed module, which is simultaneously constrainted by SMCA-loss and cycle consistency loss. 

Furthermore, I don't agreee  " it can be said that the feedback module is replaced with SAMC-loss", **because they are different concepts, i.e., the feedback module is a  neural  module and SAMC-loss is a loss function**. Meanwhile, our initial paper has frequently cited this work (pages 1,2,3,5,8) and took it into serial considerations. Please check it carefully.

As for the codes, we develop our model based the codes of [TF-VAEGAN](https://github.com/akshitac8/tfvaegan) and [cycle-CLSWGAN](https://github.com/rfelixmg/frwgan-eccv18). We have thanked them in Acknowledgement section on [code page ](https://github.com/shiming-chen/FREE/blob/main/README.md).

If you have any other doubts, pelease don't hesitate to contact me.

best!
